### ISSUE TITLE
Estado de la practica

### ISSUE THREAD

**Issue by YuranyZura** [cos4h/PracticaGitPoliJic#10]

**Comment by pkgzx** [comment]
Aque se refiere esto?

**Comment by pkgzx** [comment]
Que tendria quu hacer?, por fa añade la label esta al lado derecho es enhacement

**Comment by YuranyZura** [comment]
Por ejemplo una referencia del grupo malisimo, regularo o mejorando solo un comentario

**Comment by pkgzx** [comment]
ok
